[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "compatibility: upstream screwfinity compatibility artifacts",
    "screwfinity_large",
    "screwfinity_medium",
    "screwfinity_small",
    "screwfinity_medium_wide",
    "screwfinity_medium_wide_4u",
]

[tool.ruff]
exclude = [
    "gridfinity-rebuilt-openscad/",
    "MCAD/",
]

[tool.ruff.lint]
select = ["ALL"]
