[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "compatibility: upstream screwfinity compatibility artifacts",
]

[tool.ruff]
exclude = [
    "gridfinity-rebuilt-openscad/",
    "MCAD/",
]

[tool.ruff.lint]
select = ["ALL"]
