[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "compatibility: upstream screwfinity compatibility artifacts",
    "screwfinity-large",
    "screwfinity-medium",
    "screwfinity-small",
    "screwfinity-medium-wide",
    "screwfinity-medium-wide-4u",
]

[tool.ruff]
exclude = [
    "gridfinity-rebuilt-openscad/",
    "MCAD/",
]

[tool.ruff.lint]
select = ["ALL"]
