name: "CI"
on:
    - pull_request
    - push

env:
    USE_PYTHON_VERSION: "3.12.5"
    USE_PIPENV_VERSION: "2024.0.1"

jobs:
    ci:
        strategy:
            fail-fast: true
            matrix:
                openscad-version: ["2021.01"]
                os: ["ubuntu-latest"]
                script: ["./build.sh", "./compat.sh"]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4.1.7
              with:
                submodules: true
            - uses: ConorMacBride/install-package@3e7ad059e07782ee54fa35f827df52aae0626f30
              with:
                apt: openscad
                brew: openscad
            - uses: actions/setup-python@v5.2.0
              with:
                python-version: ${{ env.USE_PYTHON_VERSION }}
                cache: "pipenv"
            - uses: tiagovrtr/actions-pipenv@42dd846ed39aab687919c45dd5e80e448f0da503
              with:
                pipenv-version: ${{ env.USE_PIPENV_VERSION }}
            - run: pipenv install
            - name: "run tests"
              run: ${{ matrix.script }}
            - name: "upload test vector results"
              if: ${{ always() }}
              uses: actions/upload-artifact@v4.4.0
              with:
                name: "vector-results_${{ matrix.os }}_${{ matrix.openscad-version }}"
                path: "build/vectors/"
                if-no-files-found: "error"
