name: "CI"
on:
    - pull_request
    - push

jobs:
    ci:
        strategy:
            fail-fast: true
            matrix:
                openscad-version: ["2021.01"]
                python-version: ["3.12.5"]
                pipenv-version: ["2024.0.1"]
                os: ["ubuntu-latest"]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true
            - uses: ConorMacBride/install-package@3e7ad059e07782ee54fa35f827df52aae0626f30
              with:
                apt: openscad
                brew: openscad
            - uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
                cache: "pipenv"
            - uses: tiagovrtr/actions-pipenv@42dd846ed39aab687919c45dd5e80e448f0da503
              with:
                pipenv-version: ${{ matrix.pipenv-version }}
            - run: pipenv install
            - name: "run tests"
              run: ./build.sh
            - name: "upload test vector results"
              uses: actions/upload-artifact@v4
              with:
                name: "vector-results"
                path: "build/vectors/"
                if-no-files-found: "fail"
